// @@include('libs/flatpickr.js', {})
@@include('libs/aos.js', {})
@@include('libs/fancybox.js', {})
@@include('libs/choices.min.js', {})
@@include('libs/datepicker-full.min.js', {})
// @@include('libs/tippymin.js', {})
@@include('libs/inputmask.min.js', {})
@@include('libs/swiper.js', {})
@@include('libs/smoothScroll.js', {})
@@include('libs/wNumb.min.js', {})
@@include('libs/nouisliderr.js', {})
